### PR TITLE
Add possibility to setup firebase options when initializing app

### PR DESCRIPTION
**Pull request by Akaban**
Hello @andrewrosss ,

I'm just adding the possibility to give the library additional options when calling firebase.initialize_app, for example I use it to define the bucket default storage path.

If you'd like to merge it, would be nice :)

Thanks for the good work, the project is working nicely !

Bye

### CODE REVIEW

**Comment by andrewrosss** [comment]
Hey, thanks for the PR! This makes total sense to be able to target that configuration argument.

To keep supplying the configuration consistent, would you mind moving that config so that it's read from `app.config`? (for example, in the same way that `"FIREBASE_ADMIN_CREDENTIAL"` is handled).

Something like:

```python
class FirebaseAdmin(object):

    def __init__(self, app: Flask = None) -> None:  # <-- Just app here
        ...

    def init_app(self, app: Flask) -> None:  # <-- Just app here as well
        app.config.setdefault("FIREBASE_ADMIN_CREDENTIAL")
        app.config.setdefault("FIREBASE_ADMIN_OPTIONS")  # <-- set default to be None
        app.config.setdefault(
            "FIREBASE_ADMIN_AUTHORIZATION_SCHEME",
            FIREBASE_ADMIN_AUTHORIZATION_SCHEME,
        )
        app.config.setdefault(
            "FIREBASE_ADMIN_CHECK_REVOKED", FIREBASE_ADMIN_CHECK_REVOKED
        )
        app.config.setdefault(
            "FIREBASE_ADMIN_PAYLOAD_ATTR", FIREBASE_ADMIN_PAYLOAD_ATTR
        )

        cred = app.config["FIREBASE_ADMIN_CREDENTIAL"]
        options = app.config["FIREBASE_ADMIN_OPTIONS"]  # <-- read options from config, either None (from above) or a user-specified value
        self._admin = firebase_admin.initialize_app(cred, options=options)
```

This way you'd be able to setup the extension with something like:

```python
app = Flask(__name__)
app.config["FIREBASE_ADMIN_CREDENTIAL"] = credentials.Certificate("/path/to/key.json")
app.config["FIREBASE_ADMIN_OPTIONS"] = { "storageBucket": "my-bucket", ... }  # <--
firebase = FirebaseAdmin(app)
```

**Comment by Akaban** [comment]
Hey,

Of course, that was actually a quick fix to make my app work. Your solution is way better. PR updated. :)

Bye

**Comment by Akaban** [comment]
And just squashed my commit with the initial commit, so it's cleaner

**Comment by andrewrosss** [comment]
Thanks this is perfect. Merging!

**Pull request merged**
